# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'credits.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Credits(object):
    def setupUi(self, Credits):
        Credits.setObjectName("Credits")
        Credits.resize(600, 400)
        self.versionLabel = QtWidgets.QLabel(Credits)
        self.versionLabel.setGeometry(QtCore.QRect(10, 180, 571, 20))
        self.versionLabel.setText("")
        self.versionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.creditsLabel = QtWidgets.QLabel(Credits)
        self.creditsLabel.setGeometry(QtCore.QRect(10, 210, 571, 101))
        self.creditsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.creditsLabel.setWordWrap(True)
        self.creditsLabel.setObjectName("creditsLabel")
        self.imageLabel = QtWidgets.QLabel(Credits)
        self.imageLabel.setGeometry(QtCore.QRect(39, 30, 512, 140))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.mrgamedood = QtWidgets.QLabel(Credits)
        self.mrgamedood.setGeometry(QtCore.QRect(144, 350, 111, 20))
        self.mrgamedood.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mrgamedood.setAlignment(QtCore.Qt.AlignCenter)
        self.mrgamedood.setWordWrap(True)
        self.mrgamedood.setObjectName("mrgamedood")
        self.deltaboi = QtWidgets.QLabel(Credits)
        self.deltaboi.setGeometry(QtCore.QRect(344, 350, 111, 20))
        self.deltaboi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deltaboi.setAlignment(QtCore.Qt.AlignCenter)
        self.deltaboi.setWordWrap(True)
        self.deltaboi.setObjectName("deltaboi")
        self.gitLink = QtWidgets.QLabel(Credits)
        self.gitLink.setGeometry(QtCore.QRect(230, 320, 131, 21))
        self.gitLink.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gitLink.setAlignment(QtCore.Qt.AlignCenter)
        self.gitLink.setWordWrap(True)
        self.gitLink.setObjectName("gitLink")

        self.retranslateUi(Credits)
        QtCore.QMetaObject.connectSlotsByName(Credits)

    def retranslateUi(self, Credits):
        _translate = QtCore.QCoreApplication.translate
        Credits.setWindowTitle(_translate("Credits", "Credits"))
        self.creditsLabel.setText(_translate("Credits", "Razor Music Player is a project started by MrGameCub3 and Delta which was abandoned in November of 2021. Through boredom via Spring Break, we managed to completely restart the project anew and breathe new life to an application which, we hope, will make your experience listening to music much more convenient."))
        self.mrgamedood.setText(_translate("Credits", "MrGameCub3"))
        self.deltaboi.setText(_translate("Credits", "Delta"))
        self.gitLink.setText(_translate("Credits", "Project on Github"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Credits = QtWidgets.QDialog()
    ui = Ui_Credits()
    ui.setupUi(Credits)
    Credits.show()
    sys.exit(app.exec_())
