# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'miniplayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mini(object):
    def setupUi(self, Mini):
        Mini.setObjectName("Mini")
        Mini.resize(240, 205)
        self.thumbnailLabel = QtWidgets.QLabel(Mini)
        self.thumbnailLabel.setGeometry(QtCore.QRect(0, 0, 240, 134))
        self.thumbnailLabel.setText("")
        self.thumbnailLabel.setObjectName("thumbnailLabel")
        self.stackedWidget = QtWidgets.QStackedWidget(Mini)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 154, 240, 51))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.playButton = QtWidgets.QPushButton(self.page_2)
        self.playButton.setGeometry(QtCore.QRect(104, 10, 32, 32))
        self.playButton.setText("")
        self.playButton.setObjectName("playButton")
        self.stackedWidget.addWidget(self.page_2)
        self.progressBar = QtWidgets.QSlider(Mini)
        self.progressBar.setGeometry(QtCore.QRect(30, 140, 181, 20))
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Mini)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Mini)

    def retranslateUi(self, Mini):
        _translate = QtCore.QCoreApplication.translate
        Mini.setWindowTitle(_translate("Mini", "Miniplayer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mini = QtWidgets.QWidget()
    ui = Ui_Mini()
    ui.setupUi(Mini)
    Mini.show()
    sys.exit(app.exec_())
