# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'terms.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Terms(object):
    def setupUi(self, Terms):
        Terms.setObjectName("Terms")
        Terms.resize(600, 400)
        self.versionLabel = QtWidgets.QLabel(Terms)
        self.versionLabel.setGeometry(QtCore.QRect(10, 20, 571, 20))
        self.versionLabel.setText("")
        self.versionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.termsLabel = QtWidgets.QLabel(Terms)
        self.termsLabel.setGeometry(QtCore.QRect(10, 120, 571, 161))
        self.termsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.termsLabel.setWordWrap(True)
        self.termsLabel.setObjectName("termsLabel")
        self.declineButton = QtWidgets.QPushButton(Terms)
        self.declineButton.setGeometry(QtCore.QRect(160, 340, 80, 24))
        self.declineButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.declineButton.setObjectName("declineButton")
        self.acceptButton = QtWidgets.QPushButton(Terms)
        self.acceptButton.setGeometry(QtCore.QRect(360, 340, 80, 24))
        self.acceptButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.acceptButton.setObjectName("acceptButton")

        self.retranslateUi(Terms)
        QtCore.QMetaObject.connectSlotsByName(Terms)

    def retranslateUi(self, Terms):
        _translate = QtCore.QCoreApplication.translate
        Terms.setWindowTitle(_translate("Terms", "Terms"))
        self.termsLabel.setText(_translate("Terms", "Razor is made by MrGameCub3 and MCMi460 on Github. Currently, there are no terms and services, but once we get around to making those, please click either accept or deny as shown below.\n"
"\n"
"(Pressing Accept will not do anything as it only agrees to this version of the document. Each and every time the document is updated, the version number must be as well, so your acceptance of this block of text is meaningless when saved on your config file.)"))
        self.declineButton.setText(_translate("Terms", "Decline"))
        self.acceptButton.setText(_translate("Terms", "Accept"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Terms = QtWidgets.QDialog()
    ui = Ui_Terms()
    ui.setupUi(Terms)
    Terms.show()
    sys.exit(app.exec_())
