name: 'Build Razor'
on:
  release:
    types: [published]

jobs:
  build:
    name: 'Build Razor'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.11.3

    # Windows Build
    - name: 'Build'
      if: matrix.os == 'windows-latest'
      run: |
        cd scripts &&
        ./build.bat

    - name: 'Upload Build'
      if: matrix.os == 'windows-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: dist/Razor.exe

    # MacOS Build
    - name: 'Build'
      if: matrix.os == 'macos-latest'
      run: |
        cd scripts &&
        ./build.sh &&
        cd ../dist &&
        zip -yr mac.zip Razor.app/

    - name: 'Upload Build'
      if: matrix.os == 'macos-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: dist/mac.zip
